"""
routers/dashboard.py -- server-rendered dashboard pages (Jinja2).

Data is loaded client-side by small fetch() calls to /api/admin/* (see the
templates + static/app.js), so these handlers mostly just pick the template and
enforce the admin session. Login/logout live here too.
"""

import os
import re
import secrets

from fastapi import APIRouter, Depends, Form, Request, UploadFile, File, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session

from .. import models, settings
from ..auth import require_admin, require_admin_page, verify_admin_login
from ..db import get_db
from ..service import bump_and_audit

# app/routers/dashboard.py -> up 3 = server/ ; templates live at server/templates
_server_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_templates_dir = os.path.join(_server_dir, "templates")
templates = Jinja2Templates(directory=_templates_dir)

# THREE routers, deliberately, because they need three different auth answers.
#
# This used to be one router where every page handler called an inline
# _page() helper that checked the session itself. That is opt-in security: a
# handler that forgets the call is silently public, and nothing catches it --
# not review, not tests, not runtime. The guard now lives on the router, so a
# new page is protected by default and you would have to actively move it to
# `public_router` to expose it. tests/test_route_auth.py enforces this.
public_router = APIRouter(tags=["auth"])
router = APIRouter(tags=["dashboard"], dependencies=[Depends(require_admin_page)])
api_router = APIRouter(tags=["dashboard-api"], dependencies=[Depends(require_admin)])

# Filenames are generated by upload_reference_frame() as
# "<camera-uuid>_<8 hex>.<ext>", never taken from the client. Anything else is
# not one of ours.
_SAFE_FRAME_NAME = re.compile(r"[A-Za-z0-9._-]{1,128}")


@public_router.get("/login", response_class=HTMLResponse)
def login_page(request: Request):
    return templates.TemplateResponse("login.html", {"request": request, "error": None})


@public_router.post("/login")
def login_submit(request: Request, username: str = Form(...), password: str = Form(...)):
    if verify_admin_login(username, password):
        request.session["admin_user"] = username
        return RedirectResponse("/", status_code=303)
    # Deliberately generic: never reveal whether the username exists.
    return templates.TemplateResponse("login.html", {"request": request, "error": "Invalid credentials"}, status_code=401)


@public_router.get("/logout")
def logout(request: Request):
    request.session.clear()
    return RedirectResponse("/login", status_code=303)


def _page(request: Request, name: str, ctx: dict | None = None):
    """Render a dashboard template. Auth is already guaranteed by the router
    dependency, so this only assembles context."""
    base = {"request": request, "admin_user": request.session.get("admin_user", "")}
    base.update(ctx or {})
    return templates.TemplateResponse(name, base)


@router.get("/", response_class=HTMLResponse)
def overview(request: Request):
    return _page(request, "overview.html")


@router.get("/detections", response_class=HTMLResponse)
def detections_page(request: Request):
    return _page(request, "detections.html")


@router.get("/device/{device_id}", response_class=HTMLResponse)
def device_page(request: Request, device_id: str):
    return _page(request, "device.html", {"device_id": device_id})


@router.get("/device/{device_id}/cameras", response_class=HTMLResponse)
def cameras_page(request: Request, device_id: str):
    return _page(request, "cameras.html", {"device_id": device_id})


@router.get("/device/{device_id}/live", response_class=HTMLResponse)
def live_page(request: Request, device_id: str):
    return _page(request, "live.html", {"device_id": device_id})


@router.get("/device/{device_id}/roi", response_class=HTMLResponse)
def roi_page(request: Request, device_id: str):
    return _page(request, "roi_editor.html", {"device_id": device_id})


@router.get("/device/{device_id}/classes", response_class=HTMLResponse)
def classes_page(request: Request, device_id: str):
    return _page(request, "classes.html", {"device_id": device_id})


@router.get("/device/{device_id}/clip", response_class=HTMLResponse)
def clip_page(request: Request, device_id: str):
    return _page(request, "clip.html", {"device_id": device_id})


@router.get("/device/{device_id}/deterrence", response_class=HTMLResponse)
def deterrence_page(request: Request, device_id: str):
    return _page(request, "deterrence.html", {"device_id": device_id})


@router.get("/device/{device_id}/global", response_class=HTMLResponse)
def global_page(request: Request, device_id: str):
    return _page(request, "global.html", {"device_id": device_id})


@router.get("/device/{device_id}/audit", response_class=HTMLResponse)
def audit_page(request: Request, device_id: str):
    return _page(request, "audit.html", {"device_id": device_id})


# Cap the upload. `await file.read()` pulls the whole body into memory, so
# without a limit a single request is both an unbounded disk write and an
# unbounded RSS spike. A camera still is a few hundred KB.
MAX_REFERENCE_FRAME_BYTES = 8 * 1024 * 1024


# ---- reference-frame upload for the ROI editor (multipart, admin only) ----
@api_router.post("/api/admin/cameras/{cam_id}/reference-frame")
async def upload_reference_frame(
    cam_id: str,
    file: UploadFile = File(...),
    admin: str = Depends(require_admin),
    db: Session = Depends(get_db),
):
    import uuid as uuidlib
    try:
        cam = db.get(models.Camera, uuidlib.UUID(cam_id))
    except (ValueError, TypeError):
        cam = None
    if cam is None:
        raise HTTPException(404, "camera not found")

    ext = os.path.splitext(file.filename or "")[1].lower() or ".jpg"
    if ext not in (".jpg", ".jpeg", ".png"):
        raise HTTPException(400, "only jpg/png allowed")
    body = await file.read(MAX_REFERENCE_FRAME_BYTES + 1)
    if len(body) > MAX_REFERENCE_FRAME_BYTES:
        raise HTTPException(413, "reference frame too large (max 8 MB)")

    fname = f"{cam_id}_{secrets.token_hex(4)}{ext}"
    dest = os.path.join(settings.REFERENCE_FRAME_DIR, fname)
    with open(dest, "wb") as f:
        f.write(body)
    # Store the BARE FILENAME, not a URL path. These used to be served by an
    # unauthenticated StaticFiles mount, so the stored value was a public URL.
    # Serving is now an authenticated route, and keeping only the filename means
    # the serving path can change without rewriting every row.
    cam.reference_frame_url = fname
    db.commit()
    bump_and_audit(db, cam.device_id, actor=admin, table_name="cfg_cameras", row_pk=cam_id, action="reference-frame")
    return {"ok": True, "reference_frame_url": f"/api/admin/reference-frame/{fname}"}


@api_router.get("/api/admin/reference-frame/{fname}")
def get_reference_frame(fname: str, admin: str = Depends(require_admin)):
    """Serve an uploaded reference frame to an authenticated admin.

    Replaces `app.mount("/reference_frames", StaticFiles(...))`, which served
    operator-uploaded stills of EVERY customer's land to anyone who could guess
    a filename. An unguessable URL is not authorization, and it stops being even
    obscure the moment the dashboard is on a public domain.
    """
    # Reject anything that isn't a plain filename before touching the path, so
    # `..%2f..%2fetc%2fpasswd` cannot walk out of the data directory. The
    # realpath containment check below is the backstop.
    if not _SAFE_FRAME_NAME.fullmatch(fname):
        raise HTTPException(404, "not found")
    base = os.path.realpath(settings.REFERENCE_FRAME_DIR)
    path = os.path.realpath(os.path.join(base, fname))
    if os.path.commonpath([base, path]) != base or not os.path.isfile(path):
        raise HTTPException(404, "not found")
    return FileResponse(path, headers={"Cache-Control": "private, max-age=300"})
